apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: injector-webhook
spec:
  commonName: injector-webhook.svc.cluster.local
  secretName: injector-webhook-tls
  dnsNames:
    - injector-webhook.{{ .Release.Namespace }}.svc
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
