apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: injector-webhook
  annotations:
    cert-manager.io/inject-ca-from: ingress/injector-webhook
webhooks:
  - name: "io.k8s.injector-webhook"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: ingress
        name: injector-webhook
        path: /mutate
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
