apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: injector-webhook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/injector-webhook
webhooks:
  - name: "io.k8s.injector-webhook"
    objectSelector:
      matchExpressions:
        - key: "app.kubernetes.io/name"
          operator: NotIn
          values: ["injector-webhook"]
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: injector-webhook
        path: /mutate
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
